// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_API_URL: "https://brainstorm-worker.soft-sea-86fd.workers.dev";
	ASSETS: Fetcher;
}
